name: 'Android Test Report Action'
description: 'GitHub Action that prints Android test reports'
author: 'Asad Mansoor'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'file-text'
  color: 'red'
  
inputs:
  onlyFailed:
    description: 'Add to report only failed tests'
    required: false
    default: false
